experiment_id: experiment_chain-successionabANDchoiceab_3sym_20len
formula1_name: Chain succession(c0,c1)
formula2_name: Choice(c1,c2)
formula3_name: ''
formula1_index: 18
formula2_index: 13
formula3_index: null
formula1: G((c0 <-> X(c1)))
formula2: F c1 | F c2
formula3: ''
num_symbols: 3
max_length_traces: 20
train_size_traces: 0.5
mutually_exclusive_symbols: true
cnn_model: untrained_CNN_ME_state_dict_3sym.pth
hyperparameters:
  batch_size: 64
  learning_rate: 0.001
  num_epochs: 20
seed: 42
