experiment_id: experiment_chain-responsea-b_2sym_10len
formula1_name: Chain response(c0, c1)
formula2_name: ''
formula3_name: ''
formula1_index: 8
formula2_index: null
formula3_index: null
formula1: G(c0 -> X c1)
formula2: ''
formula3: ''
num_symbols: 2
max_length_traces: 10
train_size_traces: 0.5
mutually_exclusive_symbols: true
cnn_model: untrained_CNN_ME_state_dict_2sym.pth
hyperparameters:
  batch_size: 64
  learning_rate: 0.001
  num_epochs: 20
seed: 42
