experiment_id: experiment_initaANDalternate-responseabANDchoiceab_4sym_5len
formula1_name: Init(c0)
formula2_name: Alternate response(c1,c2)
formula3_name: Choice(c2,c3)
formula1_index: 0
formula2_index: 5
formula3_index: 13
formula1: c0
formula2: G( c1 -> X (! c1 U c2))
formula3: F c2 | F c3
num_symbols: 4
max_length_traces: 5
train_size_traces: 0.5
mutually_exclusive_symbols: true
cnn_model: untrained_CNN_ME_state_dict_4sym.pth
hyperparameters:
  batch_size: 64
  learning_rate: 0.001
  num_epochs: 20
seed: 42
