experiment_id: experiment_inita_2sym_20len
formula1_name: Init(c0)
formula2_name: ''
formula3_name: ''
formula1_index: 0
formula2_index: null
formula3_index: null
formula1: c0
formula2: ''
formula3: ''
num_symbols: 2
max_length_traces: 20
train_size_traces: 0.5
mutually_exclusive_symbols: false
cnn_model: untrained_CNN_NME_state_dict_2sym.pth
hyperparameters:
  batch_size: 64
  learning_rate: 0.001
  num_epochs: 20
seed: 21
