experiment_id: experiment_alternate-succesiona-b_2sym_5len
formula1_name: Alternate succesion(c0, c1)
formula2_name: ''
formula3_name: ''
formula1_index: 7
formula2_index: null
formula3_index: null
formula1: G( c0 -> X (! c0 U c1)) & (! c1 U c0) | G (! c1)
formula2: ''
formula3: ''
num_symbols: 2
max_length_traces: 5
train_size_traces: 0.5
mutually_exclusive_symbols: true
cnn_model: untrained_CNN_ME_state_dict_2sym.pth
hyperparameters:
  batch_size: 64
  learning_rate: 0.001
  num_epochs: 20
seed: 42
