experiment_id: experiment_alternate-succesiona-bANDexactlya2ANDexclusive-choiceab_4sym_10len
formula1_name: Alternate succesion(c0, c1)
formula2_name: Exactly(c1,2)
formula3_name: Exclusive choice(c2,c3)
formula1_index: 7
formula2_index: 16
formula3_index: 19
formula1: G( c0 -> X (! c0 U c1)) & (! c1 U c0) | G (! c1)
formula2: (F(c1 & X ( F(c1)))) & !(  F(c1 & X ( F ( F (c1 & X( F(c1)))))  )  )
formula3: (F c2 | F c3) & ! (F c2 & F c3)
num_symbols: 4
max_length_traces: 10
train_size_traces: 0.5
mutually_exclusive_symbols: false
cnn_model: untrained_CNN_NME_state_dict_4sym.pth
hyperparameters:
  batch_size: 64
  learning_rate: 0.001
  num_epochs: 20
seed: 21
