experiment_id: experiment_successionabANDprecedenceab_3sym_20len
formula1_name: Succession(c0,c1)
formula2_name: Precedence(c1,c2)
formula3_name: ''
formula1_index: 4
formula2_index: 3
formula3_index: null
formula1: G( c0 -> F c1) & ((! c1 U c0) | G (! c1))
formula2: (! c2 U c1) | G (! c2)
formula3: ''
num_symbols: 3
max_length_traces: 20
train_size_traces: 0.5
mutually_exclusive_symbols: false
cnn_model: untrained_CNN_NME_state_dict_3sym.pth
hyperparameters:
  batch_size: 64
  learning_rate: 0.001
  num_epochs: 20
seed: 21
