experiment_id: experiment_initaANDco-existenceabANDalternate-precedenceab_4sym_5len
formula1_name: Init(c0)
formula2_name: Co-existence(c1,c2)
formula3_name: Alternate precedence(c2,c3)
formula1_index: 0
formula2_index: 17
formula3_index: 6
formula1: c0
formula2: (F(c2)) -> (F(c1))
formula3: (! c3 U c2) | G(! c3) & G (c3 -> X ((!c3 U c2) | G (!c3)))
num_symbols: 4
max_length_traces: 5
train_size_traces: 0.5
mutually_exclusive_symbols: true
cnn_model: untrained_CNN_ME_state_dict_4sym.pth
hyperparameters:
  batch_size: 64
  learning_rate: 0.001
  num_epochs: 20
seed: 42
